version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      frontend-production-minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      frontend-development-minor:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      python-minor:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: python
        update-types: ["version-update:semver-major"]

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
